[workspace]
authors = ["Sangeetha Nandakumar <98574336+sangeethankumar@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "personal-website"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
hugo = ">=0.152.2,<0.153"
jupyter = ">=1.1.1,<2"
