baseURL = 'https://sangeethankumar.github.io/personal-website/'
languageCode = 'en-us'
title = 'Sangeetha Nandakumar'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

publishDir = "docs"
